wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1668188062.458322
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 4
      - 8
      - 13
      - 23
      - 37
      4: 3.8.10
      5: 0.13.4
      8:
      - 1
      - 5
      10:
      - 9
